{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    spaceone.service: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      spaceone.service: {{ .Values.name }}
  template:
    metadata:
      annotations:
        spaceone.deployment.tool: helm
      labels:
{{ include "spaceone.labels" . | indent 8 }}
        spaceone.service: {{ .Values.name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.gracePeriod }}
      containers:
        
        - name: docs
          image: {{ .Values.image.name }}:{{ .Values.image.version }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ['nginx', '-g', 'daemon off;']
          ports:
            - containerPort: 80
      
{{- end }}