{{- if .Values.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{- if not (eq $key "nil") }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    spaceone.service: ingress
  name: alb-ingress-docs
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}

spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation

    - host: {{ .Values.endpoint }}
      http:
        paths:
          - backend:
              serviceName: docs
              servicePort: 80
            path: /*
    - host: www.{{ .Values.endpoint }}
      http:
        paths:
          - backend:
              serviceName: redirect-to-non-www
              servicePort: use-annotation
            path: /*


  


{{- end }}
